# Building Social Media Clone API with FastAPI

from fastapi import FastAPI
from fastapi.params import Body # Body is used to define the request body for a POST or PUT request. It allows us to specify the expected structure of the data that will be sent in the request body.
from pydantic import BaseModel
from typing import Optional
from random import randrange
app=FastAPI()
class Post(BaseModel):
    title: str
    content: str 
    published : bool =True
    rating: Optional[float]=None

my_posts=[{'title':'title of post 1', 'content':'content of post 1', 'id':1},{'title':'My favourtie food','content':'I love biryani','id':2}]


@app.get("/")
def read_root():                    # Async is used only when we have to do some I/O operations like database calls, file handling, etc. It is not necessary to use async if we are just returning a simple response.
    return {"Hello": "World"}               # In normal function , we can just use def instead of async def.
 
@app.get("/posts")
def get_posts():
    return {"data":my_posts}

@app.post("/createposts")
def create_posts(NewPost: Post):
  #  print(NewPost.model_dump()) # Model_dump() is a method provided by Pydantic's BaseModel that allows you to convert a Pydantic model instance into a dictionary. It is used to serialize the model's data into a format that can be easily manipulated or returned as a response in an API.
    post_dict=NewPost.model_dump()
    post_dict['id']=randrange(0,1000000)
    my_posts.append(post_dict) # Here, we are appending the new post to the my_posts list. The post_dict is a dictionary representation of the NewPost object, and we are adding an 'id' key to it with a random value generated by randrange(0,1000000). This allows us to assign a unique identifier to each post when it is created.
    return {"data":post_dict} 


@app.post("/publishedpost")
def published_post(published: Post):
    print(published)
    return {"data":"Post published Successfully"}

@app.post("/ratingpost")
def rating_post(rating: Post):
    print(rating)
    return {"data":"Post rated Successfully"}



# Next endpoint for retrieving a specific post by its ID
@app.get("/posts/{id}")
def get_post(id: int):
    print(id)
    return {"post_detail": f"Post with id {id} retrieved successfully"}

