from .. import models, schemas # .. refers to the parent directory , it means we are referring the above directory from the current directory i.e parent directory
from fastapi import FastAPI, Response, status, HTTPException, Depends, APIRouter
from sqlalchemy.orm import Session
from ..database import get_db
from typing import List


# Now almost all the errors are handled
# Right now the only error i.e we don't have the access to the app object so we are gonna use ROUTERS
router=APIRouter(
    prefix="/posts", # This is used to add a prefix to all the endpoints defined in this router. It means that all the endpoints defined in this router will have the prefix /posts. For example, if we define an endpoint /create in this router, then the actual endpoint will be /posts/create. This helps us to organize our code better and keep the main.py file clean. We can define all the post related endpoints in this file and then include this router in the main.py file.
    tags=["Posts"]
)
# We are using APIRouter to create a router for the post endpoints. This allows us to organize our code better and keep the main.py file clean. We can define all the post related endpoints in this file and then include this router in the main.py file.
# we will replace the app object with router object in all the endpoints defined in this file. This will allow us to use the router to define the endpoints and then include this router in the main.py file.


@router.get("/",response_model=List[schemas.Post] )
def get_posts(db: Session = Depends(get_db)):
    # cursor.execute("""SELECT * FROM posts """)
    # posts=cursor.fetchall()
    # print(posts)  
    posts=db.query(models.Post).all()
    return posts

@router.post("/")
def create_posts(post: schemas.PostCreate,db: Session = Depends( get_db)): # Here, we are defining the request body for the create_posts endpoint. The post parameter is of type schemas.PostCreate, which is a Pydantic model that defines the expected structure of the data that will be sent in the request body when creating a new post. By using this model, we can ensure that the data sent in the request body is valid and conforms to the expected format for creating a new post.
  #  print(NewPost.model_dump()) # Model_dump() is a method provided by Pydantic's BaseModel that allows you to convert a Pydantic model instance into a dictionary. It is used to serialize the model's data into a format that can be easily manipulated or returned as a response in an API.
    # cursor.execute("""INSERT INTO posts(title,content,published) VALUES(%s,%s,%s) RETURNING * """,(post.title,post.content,post.published))
    ## post_dict=NewPost.model_dump()
    ## post_dict['id']=randrange(0,1000000)
    ## my_posts.append(post_dict) # Here, we are appending the new post to the my_posts list. The post_dict is a dictionary representation of the NewPost object, and we are adding an 'id' key to it with a random value generated by randrange(0,1000000). This allows us to assign a unique identifier to each post when it is created.
    # new_post=cursor.fetchone()
    # conn.commit()
    # print(**post.dict()) # The ** operator is used to unpack the dictionary returned by post.dict() and pass its key-value pairs as keyword arguments to the Post constructor. This allows us to create a new Post object with the attributes defined in the Post model, using the data provided in the request body.
    # new_post=models.Post(title=post.title, content=post.content, published=post.published)
    # Insteading of writing the above line we can also write it in a more concise way using the ** operator as shown below:
    new_post=models.Post(**post.dict())
    db.add(new_post)
    db.commit()
    db.refresh(new_post) # This is used to refresh the new_post object with the data


    return new_post




@router.post("/publishedpost")
def published_post(published: schemas.PostCreate):
    print(published)
    return {"data":"Post published Successfully"}

@router.post("/ratingpost")
def rating_post(rating: schemas.PostCreate):
    print(rating)
    return {"data":"Post rated Successfully"}



# Next endpoint for retrieving a specific post by its ID
@router.get("/{id}",response_model=schemas.Post)
def get_post(id: int,db: Session = Depends(get_db)):
    # cursor.execute("""SELECT * FROM posts WHERE id = %s """,(str(id)))
    # post=cursor.fetchone()
    post=db.query(models.Post).filter(models.Post.id==id).first() # this line is used to retrieve a specific post from the database based on its ID. The filter() method is used to specify the condition for filtering the posts, in this case, we are filtering the posts where the id column matches the provided id parameter. The first() method is used to retrieve the first result that matches the filter condition

  

    if not post:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found")
     
        # response.status_code=status.HTTP_404_NOT_FOUND
        # return {"message":f"Post with id {id} was not found"}
    return post


# Note 
# Anytime we have path parameter , its always going to return a string by default, we have to manually convert it to the type 

@router.delete("/{id}")
def delete_post(id: int,db: Session = Depends(get_db)):
    # cursor.execute("""DELETE FROM posts WHERE id=%s returning * """,(str(id),)) # we are using , after id bcos to make the execution smoother!!
    # deleted_post=cursor.fetchone()
    # conn.commit()
    post=db.query(models.Post).filter(models.Post.id==id)
    
    if post.first()==None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found")
    
    post.delete(synchronize_session=False) # synchronize_session is used to synchronize the session with the database after deleting the post. It is set to False to avoid unnecessary overhead of synchronizing the session when we are only deleting a single post. If we were deleting multiple posts, we would set it to True to ensure that the session is properly synchronized with the database after the delete operation.
    db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT) # Basically here while deleting we don't want to return any content in the response.     



# Updating the post
@router.put("/{id}",response_model=schemas.Post)

def update_post(id:int,post:schemas.PostCreate,db: Session = Depends(get_db)):
    # cursor.execute("""UPDATE posts SET title= %s, content=%s, published=%s WHERE id = %s RETURNING *""",(post.title,post.content,post.published,id))
    # updated_post=cursor.fetchone()
    # conn.commit()
    updated_post=db.query(models.Post).filter(models.Post.id==id).update(post.dict(),synchronize_session=False) # Here, we are updating the post in the database with the new data provided in the request body. The post.dict() method is used to convert the Pydantic model instance into a dictionary format that can be used for updating the database record. The synchronize_session=False parameter is used to avoid unnecessary overhead of synchronizing the session when we are only updating a single post. If we were updating multiple posts, we would set it to True to ensure that the session is properly synchronized with the database after the update operation.
    # post_to_update=updated_post.first() # This line is used to retrieve the first post that matches the filter condition, which is the post with the specified id. We need to do this because the update operation will be performed on this specific post, and we want to ensure that we are updating the correct post in the database. If there is no post with the specified id, then post_to_update will be None, and we can handle that case accordingly.
    
    if updated_post==0:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found") 
    ## post_to_update.update(post.dict(),synchronize_session=False) # Here, we are updating the post in the database with the new data provided in the request body. The post.dict() method is used to convert the Pydantic model instance into a dictionary format that can be used for updating the database record. The synchronize_session=False parameter is used to avoid unnecessary overhead of synchronizing the session when we are only updating a single post. If we were updating multiple posts, we would set it to True to ensure that the session is properly synchronized with the database after the update operation.
   # post_dict=post.model_dump()
    #post_dict['id']=id #we are assigning the same id to the updated post, so that it can replace the existing post with the same id
   # my_posts[index]=post_dict # Here, we are updating the post at the specified index in the my_posts list with the new post data. The post_dict is a dictionary representation of the updated post, and we are assigning it to the index in the my_posts list that corresponds to the post being updated.    
    db.commit()
    post_to_update=db.query(models.Post).filter(models.Post.id==id) # This line is used to retrieve the post that we just updated from the database. We need to do this because after the update operation, we want to return the updated post in the response. By querying the database again, we can ensure that we are returning the most up-to-date version of the post, which includes any changes that were made during the update operation. If there is no post with the specified id, then post_to_update will be None, and we can handle that case accordingly.
    
    return post_to_update.first() 
