# Building Social Media Clone API with FastAPI
from fastapi import FastAPI
# from fastapi.responses import Response
# from fastapi.params import Body # Body is used to define the request body for a POST or PUT request. It allows us to specify the expected structure of the data that will be sent in the request body.
from typing import Optional
# from random import randrange
from . import models
from .utils import hash_pass
from .database import Engine # . refers to the current directory
from . routers import post,user
from . routers import auth
from .config import settings

print(settings.database_password)

models.Base.metadata.create_all(bind=Engine) # This is used to create the tables in the database. It will create all the tables that are defined in the models.py file. We will use this line of code to create the tables in the database when we run the application for the first time. After that, we can comment it out or remove it from the code.


app=FastAPI()


app.include_router(post.router) # This line is used to include the post router in the main application. The post router contains all the endpoints related to posts, and by including it in the main application, we can access those endpoints when we run the application. This helps us to organize our code better and keep the main.py file clean. We can define all the post related endpoints in the post.py file and then include this router in the main.py file.
app.include_router(user.router)
app.include_router(auth.router)


# Here the raw connection with sql was there we have moved it to database.py


@app.get("/")
def read_root():                    # Async is used only when we have to do some I/O operations like database calls, file handling, etc. It is not necessary to use async if we are just returning a simple response.
    return {"Hello": "World"}               # In normal function , we can just use def instead of async def.
 
"""@app.get("/sqlalchemy")
def test_db(db: Session = Depends(get_db)):
    # Basically query is handling the sql queries
    posts=db.query(models.Post).all() # this line refers where query that gets the model.post it means table then we want all the post so will take .all()  
    print(posts)
    return {"status":'successful'}
"""





# As we know fast api has swagger UI which is automatically generated based on the endpoints we have defined in our code. We can access the swagger UI by going to http://localhost:8000/docs in our browser. This will show us a user-friendly interface where we can test our API endpoints, see the request and response formats, and interact with our API without needing to use tools like Postman or curl.
# One more is redoc which is also automatically generated by fastapi and can be accessed at http://localhost:8000/redoc. It provides a different style of documentation for our API, with a more detailed and structured layout compared to the swagger UI. Both of these documentation interfaces are very useful for testing and understanding our API endpoints.



