# Building Social Media Clone API with FastAPI
import psycopg2
from psycopg2.extras import RealDictCursor

from fastapi import FastAPI, status, HTTPException
from fastapi.responses import Response
from fastapi.params import Body # Body is used to define the request body for a POST or PUT request. It allows us to specify the expected structure of the data that will be sent in the request body.
from pydantic import BaseModel
from typing import Optional
from random import randrange
import time
from . import models
from .database import Engine, SessionLocal # . refers to the current directory


models.Base.metadata.create_all(bind=Engine) # This is used to create the tables in the database. It will create all the tables that are defined in the models.py file. We will use this line of code to create the tables in the database when we run the application for the first time. After that, we can comment it out or remove it from the code.

app=FastAPI()

# Dependency , it refers to the database session
def get_db():
    db=SessionLocal()
    try:
        yield db
    finally:
        db.close()

class Post(BaseModel):
    title: str
    content: str 
    published : bool =True
while True:
    try:
        conn= psycopg2.connect(host='localhost', database='fastapi', user='postgres',password='root@123',cursor_factory=RealDictCursor) # Cursor factory is used to specify the type of cursor that we want to use. In this case, we are using RealDictCursor which returns the query results as a list of dictionaries instead of tuples. This allows us to access the data using column names instead of index positions.
        cursor=conn.cursor()
        print("Database connection was successful")
        break
    except Exception as e:
        print("Database connection failed")
        print('Error:', e)
        time.sleep(2) # This is used to wait for 2 seconds before trying to connect to db
my_posts=[{'title':'title of post 1', 'content':'content of post 1', 'id':1},{'title':'My favourtie food','content':'I love biryani','id':2}]


@app.get("/")
def read_root():                    # Async is used only when we have to do some I/O operations like database calls, file handling, etc. It is not necessary to use async if we are just returning a simple response.
    return {"Hello": "World"}               # In normal function , we can just use def instead of async def.
 
@app.get("/posts")
def get_posts():
    cursor.execute("""SELECT * FROM posts """)
    posts=cursor.fetchall()
    print(posts)
    return {"data":posts}

@app.post("/createposts")
def create_posts(post: Post):
  #  print(NewPost.model_dump()) # Model_dump() is a method provided by Pydantic's BaseModel that allows you to convert a Pydantic model instance into a dictionary. It is used to serialize the model's data into a format that can be easily manipulated or returned as a response in an API.
    cursor.execute("""INSERT INTO posts(title,content,published) VALUES(%s,%s,%s) RETURNING * """,(post.title,post.content,post.published))
    # post_dict=NewPost.model_dump()
    # post_dict['id']=randrange(0,1000000)
    # my_posts.append(post_dict) # Here, we are appending the new post to the my_posts list. The post_dict is a dictionary representation of the NewPost object, and we are adding an 'id' key to it with a random value generated by randrange(0,1000000). This allows us to assign a unique identifier to each post when it is created.
    new_post=cursor.fetchone()
    conn.commit()
    return {"data":new_post}



def find_post(id):
    for p in my_posts:
        if p['id']==id:
            return p
    return None

def find_index_post(id):
    for i, p in enumerate(my_posts):
        if p['id']==id:
            return i
    return None


@app.post("/publishedpost")
def published_post(published: Post):
    print(published)
    return {"data":"Post published Successfully"}

@app.post("/ratingpost")
def rating_post(rating: Post):
    print(rating)
    return {"data":"Post rated Successfully"}



# Next endpoint for retrieving a specific post by its ID
@app.get("/posts/{id}")
def get_post(id: int, response: Response):
    cursor.execute("""SELECT * FROM posts WHERE id = %s """,(str(id)))
    post=cursor.fetchone()
 
    if not post:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found")
     
        # response.status_code=status.HTTP_404_NOT_FOUND
        # return {"message":f"Post with id {id} was not found"}
    return {"post_detail":post}


# Note 
# Anytime we have path parameter , its always going to return a string by default, we have to manually convert it to the type 

@app.delete("/posts/{id}")
def delete_post(id: int):
    cursor.execute("""DELETE FROM posts WHERE id=%s returning * """,(str(id),)) # we are using , after id bcos to make the execution smoother!!
    deleted_post=cursor.fetchone()
    conn.commit()

    
    if delete_post==None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found")
    
    return Response(status_code=status.HTTP_204_NO_CONTENT) # Basically here while deleting we don't want to return any content in the response.     



# Updating the post
@app.put("/posts/{id}")
def update_post(id:int, post:Post):
    cursor.execute("""UPDATE posts SET title= %s, content=%s, published=%s WHERE id = %s RETURNING *""",(post.title,post.content,post.published,id))
    updated_post=cursor.fetchone()
    conn.commit()
    
    if updated_post is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Post with id {id} was not found") 
   # post_dict=post.model_dump()
    #post_dict['id']=id #we are assigning the same id to the updated post, so that it can replace the existing post with the same id
   # my_posts[index]=post_dict # Here, we are updating the post at the specified index in the my_posts list with the new post data. The post_dict is a dictionary representation of the updated post, and we are assigning it to the index in the my_posts list that corresponds to the post being updated.    

    return {"data":updated_post} 


# As we know fast api has swagger UI which is automatically generated based on the endpoints we have defined in our code. We can access the swagger UI by going to http://localhost:8000/docs in our browser. This will show us a user-friendly interface where we can test our API endpoints, see the request and response formats, and interact with our API without needing to use tools like Postman or curl.
# One more is redoc which is also automatically generated by fastapi and can be accessed at http://localhost:8000/redoc. It provides a different style of documentation for our API, with a more detailed and structured layout compared to the swagger UI. Both of these documentation interfaces are very useful for testing and understanding our API endpoints.



