# Building Social Media Clone API with FastAPI
import psycopg2
from psycopg2.extras import RealDictCursor
from typing import List

from fastapi import FastAPI, status, HTTPException, Depends 
from fastapi.responses import Response
from fastapi.params import Body # Body is used to define the request body for a POST or PUT request. It allows us to specify the expected structure of the data that will be sent in the request body.

from typing import Optional
from random import randrange
import time
from . import models, schemas
from .utils import hash_pass
from .database import Engine, get_db # . refers to the current directory
from sqlalchemy.orm import Session

from . routers import post,user




app=FastAPI()



app.include_router(post.router) # 
app.include_router(user.router)



models.Base.metadata.create_all(bind=Engine) # This is used to create the tables in the database. It will create all the tables that are defined in the models.py file. We will use this line of code to create the tables in the database when we run the application for the first time. After that, we can comment it out or remove it from the code.



while True:
    try:
        conn= psycopg2.connect(host='localhost', database='fastapi', user='postgres',password='root@123',cursor_factory=RealDictCursor) # Cursor factory is used to specify the type of cursor that we want to use. In this case, we are using RealDictCursor which returns the query results as a list of dictionaries instead of tuples. This allows us to access the data using column names instead of index positions.
        cursor=conn.cursor()
        print("Database connection was successful")
        break
    except Exception as e:
        print("Database connection failed")
        print('Error:', e)
        time.sleep(2) # This is used to wait for 2 seconds before trying to connect to db
my_posts=[{'title':'title of post 1', 'content':'content of post 1', 'id':1},{'title':'My favourtie food','content':'I love biryani','id':2}]


@app.get("/")
def read_root():                    # Async is used only when we have to do some I/O operations like database calls, file handling, etc. It is not necessary to use async if we are just returning a simple response.
    return {"Hello": "World"}               # In normal function , we can just use def instead of async def.
 
"""@app.get("/sqlalchemy")
def test_db(db: Session = Depends(get_db)):
    # Basically query is handling the sql queries
    posts=db.query(models.Post).all() # this line refers where query that gets the model.post it means table then we want all the post so will take .all()  
    print(posts)
    return {"status":'successful'}
"""



def find_post(id):
    for p in my_posts:
        if p['id']==id:
            return p
    return None

def find_index_post(id):
    for i, p in enumerate(my_posts):
        if p['id']==id:
            return i
    return None



# As we know fast api has swagger UI which is automatically generated based on the endpoints we have defined in our code. We can access the swagger UI by going to http://localhost:8000/docs in our browser. This will show us a user-friendly interface where we can test our API endpoints, see the request and response formats, and interact with our API without needing to use tools like Postman or curl.
# One more is redoc which is also automatically generated by fastapi and can be accessed at http://localhost:8000/redoc. It provides a different style of documentation for our API, with a more detailed and structured layout compared to the swagger UI. Both of these documentation interfaces are very useful for testing and understanding our API endpoints.



